#!/bin/bash

# this script is only for linux (untested)

export JAVA_HOME="./.dev-kits/linux/jdk-18.0.1.1"
./.dev-kits/maven/mvn compile -f "./pom.xml"
$JAVA_HOME/bin/java -cp ./target/classes com.mycompany.airlinereservation.AirlineReservation
